arch:
- amd64

services:
- docker

before_install:
- docker pull postgres:15-alpine
- docker tag postgres:15-alpine registry.cn-hangzhou.aliyuncs.com/packyzbq/postgres:15-alpine
- docker login --username=jimzbq9 -p $ACS_PASSWORD registry.cn-hangzhou.aliyuncs.com 
- docker push registry.cn-hangzhou.aliyuncs.com/packyzbq/postgres:15-alpine

script:
- echo "done"
