name: Sync image to aliyun

on: push

jobs:
  sync_image_job:
    name: Sync docker image
    runs-on: ubuntu-latest
    steps:
    - name: checkout
      uses: actions/checkout@v2
    - name: pull image from docker hub
      run: |
        pwd
        bash ../image-sync/sync.sh